// <auto-generated />
package PlainEnglish;

import java.util.LinkedList;
import java.util.Optional;
import PlainEnglish.Token.TokenTypes;

public class TokenManager
{
    private final LinkedList<Token> tokens;
    public TokenManager(LinkedList<Token> tokens)
    {
        this.tokens = tokens;
    }
    
    Optional<Token> MatchAndRemove(TokenTypes type){
		return null;
    }
    
    Optional<Token> Peek(int distance){
		return null;
    	
    }
    
    public boolean nextTwoTokensMatch(Token.TokenTypes first, Token.TokenTypes second) {
    	if(first == second) {
    		return true;
    	}else {
    		return false;
    	}
    }
    
    public int getCurrentLine() {
    	return tokens.getFirst().LineNumber;
    }
    
    public int getCurrentColumn() {
    	return tokens.getFirst().ColumnNumber;
    }

}

